Added a logic to disconnect users from ServiceNow on change of the encryption secret.
mattermost/mattermost-plugin-servicenow pull request #171
Opened 2023-02-17 13:14 UTC by Nityanand13

* [MI-2032]: Modified the error when a user updates his encryption secret

* [MI-2032]: Review fixes done
1. Fixed linting errors

* [MI-2032]: Review fixes done 1.Improved code quality

* [MI-2032]: Review fixes done
1. Improved code quality

* [MI-2032]: Added a logic that if we change the encryption secret then at that time only all the users will be disconnected from service now.

* [MI-2032]: Modified code quality

* [MI-2032]: Review fixes done
1. Improved code quality

* [MI-2032]: Review fixes done
1. Implemented separate goroutine to delete users

* [MI-2032]: Review fixes done
1. Used goroutines inside a loop
2. Improved code readability

#### Summary

#### Ticket Link

2023-07-21 11:41 UTC, ayusht2810 commented
@hanzei the below PR is ready for review. Can please assign the designated reviewer to it.

2023-08-21 14:38 UTC, mickmister commented on server/plugin/configuration.go
> +	}
Shouldn't we delete the users even if the `oldEncryptionSecret` is blank? As long as the secret changed

2023-08-22 07:31 UTC, hanzei requested changes
Thanks for the PR :+1:

I'm wondering how the code behaves in a HA environment. Are there issues that can arise when multiple servers race to delete the user list?

2024-03-19 10:55 UTC, AayushChaudhary0001 approved these changes
The PR above has been tested for the following scenario:-

- On changing the encryption secret in MM, the connected users are disconnected from Servicenow.

The PR was working fine for the above condition, LGTM. Approved.

2024-03-21 07:01 UTC, Kshitij-Katiyar commented
> Thanks for the PR 👍
> 
> I'm wondering how the code behaves in a HA environment. Are there issues that can arise when multiple servers race to delete the user list?

@hanzei https://github.com/mattermost/mattermost-plugin-servicenow/pull/171#pullrequestreview-1945840706 QA tested this PR for the HA environment and its working perfectly fine.

2024-03-22 10:11 UTC, hanzei commented
I'm leaving it to @mickmister to suggest next steps on this PR

2024-03-25 10:25 UTC, hanzei commented on server/plugin/kv.go
> +	mu := new(sync.Mutex)
> We definitely want to coordinate this so it only runs on one node. We can use [cluster.Mutex](https://github.com/mattermost/mattermost/blob/7e317c7568699ddf31a43b3177ccb04168e28b8f/server/public/pluginapi/cluster/mutex.go#L41) to coordinate this. We did something similar (a "migration" of sorts) using this here https://github.com/mattermost/mattermost-plugin-gitlab/pull/361.

Strong :+1:

2024-03-25 10:26 UTC, hanzei requested changes

2024-03-25 10:26 UTC, hanzei commented on server/plugin/kv.go
> +				defer wg.Done()
Do we need to fan out the keys to different go routines as part of this PR?

2024-03-25 10:26 UTC, hanzei commented on server/plugin/kv.go
> +			s.plugin.API.LogError("Unable to delete a user", "UserID", user.MattermostUserID, "Error", err.Error())
```suggestion
			s.plugin.API.LogWarn("Unable to delete a user", "UserID", user.MattermostUserID, "Error", err.Error())
```

2024-03-25 10:26 UTC, hanzei commented on server/plugin/kv.go
> +			s.plugin.API.LogError("Unable to delete a user", "UserID", user.MattermostUserID, "Error", err.Error())
The log message should make it clear why we are deleting the user.

2024-03-25 10:27 UTC, hanzei commented on server/plugin/kv.go
> +	mu := new(sync.Mutex)
I wonder why we are fanning out the requests at all.

2024-03-29 18:16 UTC, ayusht2810 commented
@hanzei @mickmister fixed the review comments. Please re-review.

2024-05-06 17:29 UTC, ayusht2810 commented
@mickmister @hanzei Gentle reminder to re-review the PR

2024-05-13 20:42 UTC, mickmister commented
There's no customer reported ticket associated with this, so I'm not sure if this is a priority that should require this complexity

2024-05-14 10:47 UTC, Kshitij-Katiyar commented
> There's no customer reported ticket associated with this, so I'm not sure if this is a priority that should require this complexity

This was a problem we faced while developing, that's why we have added this feature as an enhancement. 
@mickmister

2024-05-14 20:42 UTC, mickmister reviewed
The PR mostly LGTM. I think the goroutines used to fetch all users may be unnecessary. Otherwise looks good :+1:

2024-05-14 20:42 UTC, mickmister commented on server/plugin/kv.go
> +			s.plugin.API.LogError("Unable to delete all users state from the store", "Error", err.Error())
I'm thinking "delete all users state" may be a bit ambiguous. Maybe we can word this as "disconnect users job running flag". Same for other similar log statements

2024-05-14 20:42 UTC, mickmister commented on server/plugin/kv.go
> +	mu := new(sync.Mutex)
Yeah I'm thinking the same now. I think we should do this synchronously here with no wait group or goroutines. @Kshitij-Katiyar What do you think?

2024-05-14 20:42 UTC, mickmister commented on server/plugin/kv.go
> +		wg.Add(1)
The wait group is actually one per page here, so I misspoke above. I'm still thinking our own database should not be used like this in this context

2024-05-16 09:06 UTC, Kshitij-Katiyar commented on server/plugin/kv.go
> +	mu := new(sync.Mutex)
yeah, I think we should do this synchronously as this is a very minor edge case as well. @mickmister

2024-06-04 09:43 UTC, ayusht2810 commented
@mickmister fixed the review comments. Please re-review

2024-06-04 14:54 UTC, mickmister reviewed
LGTM, just one suggestion to remove the lock since we're doing this synchronously now

2024-06-04 14:54 UTC, mickmister commented on server/plugin/kv.go
> +					break
If we reach an error, we should either `continue` or `return` here I think. The original strategy of `continue` seems fine to me

2024-06-04 14:54 UTC, mickmister commented on server/plugin/kv.go
> +				mu.Unlock()
We shouldn't need this lock anymore

2024-06-05 08:42 UTC, ayusht2810 commented
@mickmister fixed the review comments. Please re-review

2024-06-05 16:32 UTC, mickmister approved these changes

2024-06-06 13:31 UTC, fmartingr approved these changes
Good work. I needed a few reads to understood what was going on, left my thought in comments but not blocking.

This would be fairly useful for other plugins as well @mickmister (https://github.com/mattermost/mattermost-plugin-google-calendar/issues/61)

2024-06-06 13:31 UTC, fmartingr commented on server/plugin/kv.go
> +	deleteAllUsersMutex.Lock()
Can't we move the mutex inside the `DeleteAllUsersState` since that's the method blocked on it? Is there a reason for having it here?

2024-06-06 13:31 UTC, fmartingr commented on server/plugin/kv.go
> +func (s *pluginStore) DeleteAllUsersState() bool {
I didn't understood what this did at first. I guess this is checking if the delete all users process is running, maybe a more descriptive name or comment is in order?

2024-07-02 15:26 UTC, mickmister approved these changes

2024-12-30 05:50 UTC, arush-vashishtha approved these changes
This PR has been tested for updating the "Encryption Secret", The connected users are getting disconnected. LGTM

2024-12-30 13:09 UTC, merged