Fixed issue #172
mattermost/mattermost-plugin-servicenow pull request #182
Opened 2023-04-21 06:35 UTC by ayusht2810

#### Summary

1. Added a feature to open the incident modal using the slash command and to create incidents using the slash command.
2. Added a feature in the incident modal to subscribe to the newly created incident.
3. Added a feature to open the incident modal from post menu actions and auto-fill the "Short description" and "Description" fields with the post data.

#### Screenshots
![image](https://user-images.githubusercontent.com/100013900/233558684-34c40a3c-2a3e-4443-a734-b6eb20750eb9.png)
![image](https://user-images.githubusercontent.com/100013900/205903818-2b5b40ca-10a1-486c-bed1-c0c766bc0eff.png)

#### Ticket Link
#172

2023-05-09 10:43 UTC, trilopin requested changes
Thanks for your work @ayusht2810 

here I write some minor things I noticed from a first review:


1. distance between buttons/labels in modal seems too small



![Screenshot 2023-05-09 at 12 33 49](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4096774/184a6696-2109-4251-b9f8-0e4b528b78cd)
![Screenshot 2023-05-09 at 12 38 57](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4096774/76c70edc-afe8-4609-8ccb-a2d41b73c321)
![Screenshot 2023-05-09 at 12 39 20](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4096774/c396bae0-1664-4904-a9b0-9da171f6b52d)
![Screenshot 2023-05-09 at 12 41 07](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4096774/32a7cb32-c005-425f-906f-1b8c108ae7e8)
![Screenshot 2023-05-09 at 12 41 10](https://github.com/mattermost/mattermost-plugin-servicenow/assets/4096774/033062a1-c4ef-4991-9d2e-7c5190aaebf6)



2. add comments modal has cta button enabled before adding context inside the textarea (update state is correct)

3. Update modal raises in multiple devices at the same time, not only on the window that was triggered (it doesn't happen with the create incident modal)

2023-05-09 10:45 UTC, trilopin commented
Additionally I get `It seems that you are not authorized to manage subscriptions in ServiceNow. Please follow the instructions for setting up user permissions available in the plugin's documentation. The instructions can also be viewed by running the "/servicenow help" command.` message when I try to raise the modal with `/servicenow create incident ` (it works fine for post dialog)

I could understand that I lack permissions for subscriptions, but should they apply to create-incident? if so, should it apply for create incident from post dialog too?

2023-05-10 12:36 UTC, ayusht2810 commented
@trilopin regarding point
`3. Update-State modal raises in multiple devices at the same time, not only on the window that was triggered (it doesn't happen with the create incident modal)`. We fixed this issue previously in a PR but this caused the issue of `modals` not opening through the `Playbooks plugin`. You can refer to these issues for more detailed discussion.
https://github.com/mattermost/mattermost-plugin-servicenow/issues/120
https://github.com/mattermost/mattermost-plugin-servicenow/issues/167

2023-05-10 12:56 UTC, trilopin commented
@hanzei @mickmister

2023-05-10 16:56 UTC, ayusht2810 commented
@trilopin fixed the review fixes

2023-05-16 17:20 UTC, lieut-data approved these changes
Just a handful of comments, but nothing blocking.

2023-05-16 17:20 UTC, lieut-data commented on server/plugin/api.go
> +	}
Apologies that I'm not familiar with the overall feature here, but I'm wondering why we redirect the sharing post into the DM between the user and the bot in this case instead of just posting as the bot into the DM/GM?

It's true that the bot won't be a member of these channels, but fundamentally I don't think that prevents the bot from posting a message there. Not a blocker, but just sharing to make sure I understand the intent.

2023-05-16 17:20 UTC, lieut-data commented on server/plugin/util.go
> +func (p *Plugin) HasChannelPermissions(userID, channelID string, checkType bool) (int, model.ChannelType, error) {
I'm guessing some of this is upstream, so I won't recommend a change here, but it would be ideal to avoid boolean parameters like this in favour of explicit methods instead, e.g. `HasChannelPermissions` and `HasPublicOrPrivateChannelPermissions`. It's much easier to review the calling code instead of an obscure `, true` or `, false` addition.

2023-05-16 17:20 UTC, lieut-data commented on server/plugin/client.go
> +		constants.SysQueryParamDisplayValue: {"true"},
Can you clarify what this does?

2023-05-17 13:53 UTC, mickmister approved these changes
Just a few non-blocking comments

2023-05-17 13:53 UTC, mickmister commented on webapp/src/containers/createIncident/createIncidentMenu.tsx
> +                        src={`${Utils.getBaseUrls().publicFilesUrl}${Constants.SERVICENOW_ICON_URL}`}
We'll want to make sure we take into account the server's Site URL when contacting the plugin via HTTP. At the moment we are just parsing the browser's URL:

https://github.com/mattermost/mattermost-plugin-servicenow/blob/fefb220d1256c4e56d130beb54c30819196da598/webapp/src/utils/index.tsx#L18-L23

2023-05-17 13:53 UTC, mickmister commented on server/plugin/command.go
>  			}
Can we instead have this if statement be a "positive" one? Meaning, instead of adding exception cases, we check for the specific case(s) where we should run the if block. This way we don't need to update this condition when we add more features.

2023-05-17 21:21 UTC, DHaussermann commented
HI @ayusht2810 
I have done a round of testing on this and it seems to be working. I still have some edge cases to explore and such. 

I do have a coupe questions with the business logic on the "caller" field. From what I can tell...
- When creating an incident not based on a post - the creator may assign any Service Now user as the caller. 
- When creating an incident based on a post of a user **not** connected to Service Now -  the creator may assign any Service Now user as the caller.  
- When creating an incident based on a post of a user who **is** connected to Service Now - The author of the post must be assigned as the caller
Is this ☝️ correct?

If so... 

1. Are we certain we want to enforce that the author of the post must be the caller if they are connected to Service Now? As it is, the short description can be edited from the post content and it may be the case that you want to create an incident based on another users post
2. When using slash command to create (or creating based on a post from a user not connected to SN) any user can be the caller. The problem is that both the Mattermost username and the ServiceNow username are shown. 
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/3d43dc2f-5e21-4bea-a083-1f39987270ee)
In this image - both users are the same person and called will be `abel.tutor` in SN regardless of which option I select. Can we add some kind of logic to hide Mattermost username if Service Now username is already included? I am worried this could cause alot of "duplication" and confusion.

3. When caller is locked to the author of the post, can the field be read-only? Even though there is not affect on the SN side, it could be confusing that they can attempt to change this value
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/34945602-fdee-4db8-a0fa-645a3102b2ac)

2023-05-18 16:26 UTC, DHaussermann commented
Hi @ayusht2810 I have only a couple things to add from my test pass. 

4. Short description field should be capped at 160 (or 161) characters in the modal text field. On Service Now side the field only holds 161 characters. The remaining characters are silently discarded.
5. 0/5 minor UX point - The channel and user pickers are a bit odd as the styling is different from other plugins. But also, it's different because you must clear out the current selection to pick something else rather then seeing a drop down to make a change.

2023-05-30 07:53 UTC, ayusht2810 commented on server/plugin/client.go
> +		constants.SysQueryParamDisplayValue: {"true"},
this query param helps in retrieving the display values instead of their IDs for the fields

2023-05-30 08:07 UTC, ayusht2810 commented
> HI @ayusht2810 I have done a round of testing on this and it seems to be working. I still have some edge cases to explore and such.
> 
> I do have a coupe questions with the business logic on the "caller" field. From what I can tell...
> 
> * When creating an incident not based on a post - the creator may assign any Service Now user as the caller.
> * When creating an incident based on a post of a user **not** connected to Service Now -  the creator may assign any Service Now user as the caller.
> * When creating an incident based on a post of a user who **is** connected to Service Now - The author of the post must be assigned as the caller
>   Is this point_up correct?

Yes, the above behavior is correct. But in the 3rd point, we are not restricting the caller. The caller field can be configured. Also, the reason for having this field configured is if the system admin wants to make an incident on behalf of some other user, he can change the caller value for that particular incident.

> If so...
> 
> 1. Are we certain we want to enforce that the author of the post must be the caller if they are connected to Service Now? As it is, the short description can be edited from the post content and it may be the case that you want to create an incident based on another users post
> 2. When using slash command to create (or creating based on a post from a user not connected to SN) any user can be the caller. The problem is that both the Mattermost username and the ServiceNow username are shown.
>    ![image](https://user-images.githubusercontent.com/35588783/239079209-3d43dc2f-5e21-4bea-a083-1f39987270ee.png)
>    In this image - both users are the same person and called will be `abel.tutor` in SN regardless of which option I select. Can we add some kind of logic to hide Mattermost username if Service Now username is already included? I am worried this could cause alot of "duplication" and confusion.

We are not able to reproduce this issue. Can you please re-verify whether both the users are the same user or different one?

> 3. When caller is locked to the author of the post, can the field be read-only? Even though there is not affect on the SN side, it could be confusing that they can attempt to change this value
>    ![image](https://user-images.githubusercontent.com/35588783/239080073-34945602-fdee-4db8-a0fa-645a3102b2ac.png)

2023-05-30 08:12 UTC, ayusht2810 commented
> 5. 0/5 minor UX point - The channel and user pickers are a bit odd as the styling is different from other plugins. But also, it's different because you must clear out the current selection to pick something else rather then seeing a drop down to make a change.

@DHaussermann we are using an `Auto Suggest` component here instead of a drop-down. That's why the behavior is like this.

2023-05-31 14:48 UTC, raghavaggarwal2308 commented
@mickmister Fixed the review comments mentioned by you

2023-06-06 15:22 UTC, DHaussermann commented
On 1 . 
>"But in the 3rd point, we are not restricting the caller. The caller field can be configured."

Maybe I'm misunderstanding... But, when the author of the post is mapped to Service Now, I see no obvious way to change the value..

Mapped User
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/254ebd9f-93d7-4daf-9765-f0ae9aba2725)


Unmapped User
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/202a8258-18ec-4162-b7eb-5670a2cd5b52)


On 2. I can no longer see the duplication but, only the Mattermost usernames are shown not the Service Now user names please confirm this is correct.

On 3. whats happening here is this control - It's actually unclear what is selected  and what text is just the search term. So, if I search for something that does not match anything, I can then submit with my search term and it's not obvious what is selected. This is what caused my confusion. Can you force me to select something?
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/c170673d-75aa-46ae-929a-6fc67e36a5ef)

2023-06-06 15:26 UTC, DHaussermann commented
@raghavaggarwal2308 I'm sorry the comment above ☝️  did not save yesterday but, I meant to @ mention you.

2023-06-15 08:41 UTC, raghavaggarwal2308 commented
@DHaussermann 
1. I think there is a misunderstanding. Since this is a search component, not a dropdown, we must remove the typed value to see all available options. Currently, it's showing all the options matching the typed value.

2. Yes, it's correct, we are showing the mattermost usernames.

3. If the user does not select any value from the list and types any random value and submits then the default value will be empty(We are taking an assumption that it's obvious for the user to select a value and not just type it). Since this field is not mandatory for sending in the ServiceNow API, we are not forcing the user to select a value.

2023-06-15 15:59 UTC, DHaussermann commented
@raghavaggarwal2308 

1. Yes I was confused. Without the `x` I saw no obvious way to change the value (without backspacing out with keystrokes).    

3. The addition of the `x` to clear a selected value improves many things 
- It is now a bit more clear what is selected Vs what is a search term
- There is an obvious way to clear the value 
- We're forcing the user to acknowledge they've cleared the value because they begin searching which to me makes it more obvious what's happening

With these changes, I feel okay with the user picker. 👍 

@raghavaggarwal2308 I think we're good on the above ☝️ 

I see an unrelated issue where on 1st login the user does not get the icon. The webapp must be refreshed. This does not only happen on HA.   
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/006d1113-459e-4b5c-99ad-d59cc900556e)

I don't know if this will get solved when we cut a release or maybe it has already existed. This change must still be cherry-picked into the 2.x.x brach correct? If so, maybe I should just open a new issue if I see it occurring there?

2023-06-16 12:06 UTC, raghavaggarwal2308 commented
@DHaussermann What do you exactly mean by the first login here? We tried re-deploying the plugin and connecting again but the issue is not reproducible on our local.

2023-06-16 12:53 UTC, DHaussermann commented
hi @raghavaggarwal2308 
When you create an account and login to Mattermost for the first time. It's possible this is a broader issue with App Bar but I don't think it's happening for the other icons. 

1. Install and enable the SN plugin
2. Get an invite link to a team (can use https://dkh-service-now.test.mattermost.cloud/signup_user_complete/?id=b71wyfc76bbidxg4pas8syocho)
3. Follow the link (in a new browser session if you're already logged in)
4. Create an account and login
**Observed**: The SN app bar icon is missing until you refresh.

2023-06-16 13:17 UTC, DHaussermann commented
@raghavaggarwal2308  one more note on this ☝️ 

I've been using `6.3.0` as a test server. But I'm not sure that's valid as I hit other unrelated webapp issues. 

That being said - I do see this on the last 6.3.x release as well `6.3.6`

![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/e61f13da-de83-4152-ae1f-ff8d08e68df4)



Also confirmed another App Bar plugin Zoom does not seem affected.

2023-06-19 12:49 UTC, raghavaggarwal2308 commented
@DHaussermann The icon issue should be fixed now. Can you please confirm?

2023-06-20 21:13 UTC, DHaussermann approved these changes
Tested and passed
Icon and all other know issues are now resolved.

LGTM!

2023-06-20 21:17 UTC, DHaussermann commented
@raghavaggarwal2308 Thanks for the effort on this. I have 2 related questions that do no block the PR.

1. Do you know what's happening with the App Bar? This plugin shows in the app bar even when it does not seem enabled for  other plugins (see below) I imagine this is intentional. Do you recall anything about this plugin always showing in the app bar?
![image](https://github.com/mattermost/mattermost-plugin-servicenow/assets/35588783/a91c8506-ccf9-4b91-a7b4-1dfaa3635a20)

2. Can you please clarify for me if this PR will now be cherry picked to a v`2.x.x` branch?

2023-06-22 11:15 UTC, raghavaggarwal2308 commented
@DHaussermann 
1. Not sure what you are saying here. The icon is not visible when we disable the plugin or the app bar. Can you please send us the steps to reproduce the issue?
2. The issue #172 was to move the create incident dialog from v3.x.x to v2.x.x. So, once this PR is merged we will create a new v2.x.x release.

2023-06-23 15:35 UTC, DHaussermann commented
1. Yes I suppose you have answered my question as that is the issue. 
To clarify, when the app bar is disabled, the icon will not show in the channel header the way the other icons do. This must be by design and I simply don't recall. Can you find a technical reason why the icon does not show in the channel header? This was done intentionally correct?

2. Thanks. I understand 👍

2023-06-23 15:35 UTC, DHaussermann commented
@raghavaggarwal2308 sorry I missed the at mention for you ☝️

2023-06-23 15:43 UTC, raghavaggarwal2308 commented
@DHaussermann The icon will be visible in the channel header when the app bar is disabled but the icon color will be changed. Please check the below screenshots. Let me know if you are unable to see the icon.
![Screenshot from 2023-06-23 21-09-19](https://github.com/mattermost/mattermost-plugin-servicenow/assets/55234496/2a83fd50-1aac-4d34-89d7-e8134f1dcb92)
![Screenshot from 2023-06-23 21-09-32](https://github.com/mattermost/mattermost-plugin-servicenow/assets/55234496/8436b820-e5b2-4694-8012-77aa5abcd787)

2023-06-29 13:34 UTC, DHaussermann commented
@raghavaggarwal2308 please ping mw once we have this merged and packaged into a release for release tesing.

2023-06-29 13:51 UTC, raghavaggarwal2308 commented
@mickmister Can you please merge this PR if nothing is pending?

2023-07-05 21:32 UTC, mickmister reviewed
I gave the PR another review. In general looks good :+1: Just a few comments for discussion

2023-07-05 21:32 UTC, mickmister commented on server/plugin/util.go
>  	}
Same request here to use `HasPermissionToChannel`

2023-07-05 21:32 UTC, mickmister commented on webapp/src/containers/createIncident/subscribeToNewIncident.tsx
> +        return {isLoading, isSuccess, isError, data: data as RecordData, error: (apiErr as FetchBaseQueryError)?.data as APIError | undefined};
Can we split this up into more statements here instead of putting everything in one deconstruction and one return statement? It's not clear what's happening with all of the `as`'s.

Can `getApiState` handle the casting instead?

2023-07-05 21:32 UTC, mickmister commented on webapp/src/containers/createIncident/subscribeToNewIncident.tsx
> +    }, [getSubscriptionState().isError, getSubscriptionState().isSuccess, getSubscriptionState().isLoading]);
We could call `getSubscriptionState()` once instead of calling it 3 times here. Also, the `useEffect` callback should not be calling `getSubscriptionState` since that is "recreating" the dependencies for the callback.

Also `subscriptionPayload` needs to be added to the dependency array

```ts
const {isLoading, isError, isSuccess, error} = getSubscriptionState();

useEffect(() => {
    if (subscriptionPayload) {
        setShowModalLoader(isLoading);
        if (isError && error) {
            handleError(error);
        }

        if (isSuccess) {
            setApiError(null);
            dispatch(refetch());
            setShowResultPanel(true);
        }
    }
}, [subscriptionPayload, isError, isSuccess, isLoading]);
```

2023-07-05 21:32 UTC, mickmister commented on server/plugin/api_test.go
> +				monkey.PatchInstanceMethod(reflect.TypeOf(p), "HasChannelPermissions", func(_ *Plugin, _, _ string) (int, error) {
Ideally we mock the plugin API using `api.On`, instead of mocking the plugin's code, in order to have a more realistic test

2023-07-05 21:32 UTC, mickmister commented on webapp/src/app.tsx
> +    }, [getConnectedUserState().isLoading, getConnectedUserState().data]);
Same request to de-duplicate calls to `getConnectedUserState`, and avoid recomputing state inside of `useEffect` callback

2023-07-07 16:11 UTC, raghavaggarwal2308 commented on webapp/src/containers/createIncident/createIncidentMenu.tsx
> +                        src={`${Utils.getBaseUrls().publicFilesUrl}${Constants.SERVICENOW_ICON_URL}`}
@mickmister It's very uncommon for the SiteURL and the browser's URL to be different. We have seen in the past that in a few plugins, the functionality breaks if the URLs are different. So, most of the servers keep these URLs the same. Is there really a need for this change? Because it will add unnecessary complexity to the code.

2023-07-11 09:38 UTC, raghavaggarwal2308 commented on webapp/src/utils/index.tsx
> +    const baseUrl = Cookies.get(Constants.SiteUrl);
@mickmister In context of [this comment](https://github.com/mattermost/mattermost-plugin-servicenow/pull/182#discussion_r1256077015):
There won't be any proper way to fetch the site URL from redux every time and send it in the `getBaseUrl`, we need to use some hacks to achieve this and it will get very complicated to handle all edge cases. Also, we cannot defer the `createApi` call.

2023-07-17 10:29 UTC, ayusht2810 commented on webapp/src/utils/index.tsx
> +    const baseUrl = Cookies.get(Constants.SiteUrl);
@mickmister we have found the solution for the above issue and currently working on it.

2023-08-01 09:56 UTC, raghavaggarwal2308 commented
@mickmister FIxed the review comments mentioned by you

2023-08-01 10:12 UTC, mickmister approved these changes
LGTM, just some thoughts for improvement

2023-08-01 10:12 UTC, mickmister commented on webapp/src/containers/createIncident/createIncidentMenu.tsx
> +    const {SiteURL} = useSelector((state: GlobalState) => state.entities.general.config);
Can we put this in a separate function to avoid duplicating this logic?

```suggestion
    const siteURL = useSelector(getSiteURL);
```

2023-08-01 10:12 UTC, mickmister commented on webapp/src/utils/index.tsx
> +const getBaseUrls = (mmSiteUrl?: string): {
Easiest way to default to empty string. If we don't default to empty string, `undefined` will show up in the outout

```suggestion
const getBaseUrls = (mmSiteUrl = ''): {
```

2023-08-01 10:12 UTC, mickmister commented on webapp/src/services/index.ts
> +import {BaseQueryApi} from '@reduxjs/toolkit/dist/query/baseQueryTypes';
Is this type still useful if the import can't be resolved?

2023-08-01 10:12 UTC, mickmister commented on webapp/src/index.tsx
> +        const iconUrl = `${Utils.getBaseUrls(store.getState().entities.general.config.SiteURL).publicFilesUrl}${Constants.SERVICENOW_ICON_URL}`;
Probably good to avoid accessing `state.entities` etc. in this sort of context too.

```suggestion
        const iconUrl = `${Utils.getBaseUrls(getSiteURL(store.getState()).publicFilesUrl}${Constants.SERVICENOW_ICON_URL}`;
```

2023-09-14 09:09 UTC, raghavaggarwal2308 commented on webapp/src/services/index.ts
> +import {BaseQueryApi} from '@reduxjs/toolkit/dist/query/baseQueryTypes';
@mickmister  Yes, it's useful, we are using it as the type of parameter in `handleBaseQuery` function.

2023-09-15 12:38 UTC, raghavaggarwal2308 commented
@mickmister Fixed the review comments mentioned by you

2023-09-15 16:27 UTC, mickmister commented on webapp/src/services/index.ts
> +import {BaseQueryApi} from '@reduxjs/toolkit/dist/query/baseQueryTypes';
But if it can't be resolved, how does it work? Is it the case that your editor can resolve it, but for whatever reason resolver being used by eslint cannot find it?

2023-09-15 16:30 UTC, mickmister commented
> @raghavaggarwal2308 please ping mw once we have this merged and packaged into a release for release testing.

Merging due to @DHaussermann's approval above

2023-09-15 16:30 UTC, merged

2023-09-17 07:39 UTC, raghavaggarwal2308 commented on webapp/src/services/index.ts
> +import {BaseQueryApi} from '@reduxjs/toolkit/dist/query/baseQueryTypes';
@mickmister Yes, it is being resolved by the editor but not by eslint.

2023-09-19 21:15 UTC, mickmister commented on webapp/src/services/index.ts
> +import {BaseQueryApi} from '@reduxjs/toolkit/dist/query/baseQueryTypes';
I wonder why that's the case. I would prefer we didn't have to do this, but it's pretty negligible in this case