[MM-557] Added workflow file to add new issues to github board
mattermost/mattermost-plugin-servicenow pull request #198
Opened 2024-07-05 10:47 UTC by raghavaggarwal2308

- Added workflow file to add new issue to github board
https://github.com/orgs/mattermost/projects/9/views/1

2024-07-08 14:32 UTC, mickmister approved these changes

2024-07-08 14:55 UTC, wiggin77 approved these changes
LGTM :+1:    Let's make sure @phoinixgrr reviews before merging.

2024-11-29 09:43 UTC, toninis requested changes

2024-11-29 09:43 UTC, toninis commented on .github/issue_add.yml
> +          github-token: ${{ steps.ghapp.outputs.token }}
I do not want to share our private key to public repositories . I will create a PAT form this repo and change the code a bit .

2024-11-29 10:02 UTC, toninis approved these changes

2024-11-29 10:15 UTC, merged

2024-11-29 15:18 UTC, wiggin77 commented
@raghavaggarwal2308 is this the only repo where this automation is needed?  If there are others, then there may be a better way to add this for all.

2024-11-29 18:21 UTC, raghavaggarwal2308 commented
@wiggin77 No we need this automation in all the major plugin so that we are aware of any new issues being created. On Michael's request I have already created a PR for Gitlab, Jira, Zoom. We can create the same PR for mscal, gcal and google drive plugin. 

Please let me know if there is a better way to do this. I am aware that there is separate repo for managing the CI across the plugin. Can we use that?

2024-11-29 18:24 UTC, wiggin77 commented
> No we need this automation in all the major plugin so that we are aware of any new issues being created. On Michael's request I hav

@toninis this automation will be needed for all supported plugins.  I feel like there might be a more centralized way to achieve this as you did for the `/update-branch`  commands.  Thoughts?

2024-11-29 18:24 UTC, mattermost-build commented
Error trying to update the PR.
Please do it manually.