[MM-57194]: mark confidential settings as secret
mattermost/mattermost-plugin-servicenow pull request #201
Opened 2024-09-17 12:57 UTC by Kshitij-Katiyar

#### Summary
Marked confidential settings as secret

#### Screenshot
![Screenshot from 2024-09-17 18-20-46](https://github.com/user-attachments/assets/d3974e2d-e3df-4e79-9dcc-6ead96a385aa)

2024-09-26 12:09 UTC, raghavaggarwal2308 requested changes

2024-09-26 12:09 UTC, raghavaggarwal2308 commented on plugin.json
> +                "secret": true
no need to hide the client ID

2024-09-26 15:44 UTC, raghavaggarwal2308 commented on plugin.json
> +                "secret": true
Discussed

2024-09-26 15:45 UTC, raghavaggarwal2308 approved these changes

2024-10-01 11:09 UTC, AayushChaudhary0001 approved these changes
This PR has been tested for the webhook secret, client secret and encryption secret which get encrypted in the plugin configs, LGTM. Approved.

2024-10-22 20:09 UTC, wiggin77 approved these changes

2024-10-22 20:09 UTC, merged